/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public\model\heart.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/heart.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Heart_Full_cell.geometry} material={materials.Red} position={[-0.378, 1.38, -0.134]} />
      <mesh geometry={nodes.Heart_Full_cell001.geometry} material={materials.Red} position={[-0.97, 1.294, 0.048]} />
      <mesh geometry={nodes.Heart_Full_cell002.geometry} material={materials.Red} position={[0.56, -1.097, -0.527]} />
      <mesh geometry={nodes.Heart_Full_cell003.geometry} material={materials.Red} position={[-1.604, 0.187, 0.577]} />
      <mesh geometry={nodes.Heart_Full_cell004.geometry} material={materials.Red} position={[1.935, 0.809, -0.712]} />
      <mesh geometry={nodes.Heart_Full_cell006.geometry} material={materials.Red} position={[0.664, 1.292, -0.563]} />
      <mesh geometry={nodes.Heart_Full_cell007.geometry} material={materials.Red} position={[-1.994, -0.209, -0.489]} />
      <mesh geometry={nodes.Heart_Full_cell009.geometry} material={materials.Red} position={[1.025, -1.203, 0.783]} />
      <mesh geometry={nodes.Heart_Full_cell011.geometry} material={materials.Red} position={[0.755, 0.098, -1.07]} />
      <mesh geometry={nodes.Heart_Full_cell012.geometry} material={materials.Red} position={[-0.102, 0.836, -0.582]} />
      <mesh geometry={nodes.Heart_Full_cell013.geometry} material={materials.Red} position={[-1.394, 0.944, 1.096]} />
      <mesh geometry={nodes.Heart_Full_cell014.geometry} material={materials.Red} position={[1.462, 0.711, 0.559]} />
      <mesh geometry={nodes.Heart_Full_cell015.geometry} material={materials.Red} position={[1.527, 0.862, -1.101]} />
      <mesh geometry={nodes.Heart_Full_cell016.geometry} material={materials.Red} position={[2.103, 0.027, 0.291]} />
      <mesh geometry={nodes.Heart_Full_cell017.geometry} material={materials.Red} position={[0.037, -1.13, -0.555]} />
      <mesh geometry={nodes.Heart_Full_cell018.geometry} material={materials.Red} position={[-1.661, -0.684, -0.197]} />
      <mesh geometry={nodes.Heart_Full_cell019.geometry} material={materials.Red} position={[-1.37, 0.671, -0.53]} />
      <mesh geometry={nodes.Heart_Full_cell020.geometry} material={materials.Red} position={[-0.147, -1.904, -0.34]} />
      <mesh geometry={nodes.Heart_Full_cell021.geometry} material={materials.Red} position={[1.337, -0.77, 0.073]} />
      <mesh geometry={nodes.Heart_Full_cell022.geometry} material={materials.Red} position={[1.512, -0.508, -1.048]} />
      <mesh geometry={nodes.Heart_Full_cell023.geometry} material={materials.Red} position={[-1.098, 0.375, -1.212]} />
      <mesh geometry={nodes.Heart_Full_cell024.geometry} material={materials.Red} position={[0.652, -0.158, 1.307]} />
      <mesh geometry={nodes.Heart_Full_cell025.geometry} material={materials.Red} position={[-0.341, 0.181, -0.911]} />
      <mesh geometry={nodes.Heart_Full_cell026.geometry} material={materials.Red} position={[0.864, 0.276, 1.016]} />
      <mesh geometry={nodes.Heart_Full_cell027.geometry} material={materials.Red} position={[-0.297, -0.409, -0.57]} />
      <mesh geometry={nodes.Heart_Full_cell029.geometry} material={materials.Red} position={[-1.869, 0.89, -0.101]} />
      <mesh geometry={nodes.Heart_Full_cell030.geometry} material={materials.Red} position={[-1.945, 0.242, -0.776]} />
      <mesh geometry={nodes.Heart_Full_cell031.geometry} material={materials.Red} position={[-0.799, -0.56, 1.044]} />
      <mesh geometry={nodes.Heart_Full_cell032.geometry} material={materials.Red} position={[-1.182, -0.453, -0.871]} />
      <mesh geometry={nodes.Heart_Full_cell033.geometry} material={materials.Red} position={[1.35, 1.484, 0.218]} />
      <mesh geometry={nodes.Heart_Full_cell034.geometry} material={materials.Red} position={[1.458, 0.131, -0.84]} />
      <mesh geometry={nodes.Heart_Full_cell035.geometry} material={materials.Red} position={[0.271, -1.994, -0.406]} />
      <mesh geometry={nodes.Heart_Full_cell036.geometry} material={materials.Red} position={[0.397, -1.607, 0.377]} />
      <mesh geometry={nodes.Heart_Full_cell037.geometry} material={materials.Red} position={[-0.627, -1.287, -0.731]} />
      <mesh geometry={nodes.Heart_Full_cell038.geometry} material={materials.Red} position={[1.877, 0.002, -0.448]} />
      <mesh geometry={nodes.Heart_Full_cell039.geometry} material={materials.Red} position={[-1.833, -0.277, 0.162]} />
      <mesh geometry={nodes.Heart_Full_cell040.geometry} material={materials.Red} position={[-0.881, -1.311, 0.164]} />
      <mesh geometry={nodes.Heart_Full_cell041.geometry} material={materials.Red} position={[-1.738, -0.569, 0.661]} />
      <mesh geometry={nodes.Heart_Full_cell042.geometry} material={materials.Red} position={[-1.252, -0.643, 0.818]} />
      <mesh geometry={nodes.Heart_Full_cell043.geometry} material={materials.Red} position={[-0.279, -0.789, 0.812]} />
      <mesh geometry={nodes.Heart_Full_cell044.geometry} material={materials.Red} position={[-0.999, 0.647, 0.937]} />
      <mesh geometry={nodes.Heart_Full_cell045.geometry} material={materials.Red} position={[1.186, -0.645, -0.566]} />
      <mesh geometry={nodes.Heart_Full_cell046.geometry} material={materials.Red} position={[0.892, 1.389, 0.033]} />
      <mesh geometry={nodes.Heart_Full_cell047.geometry} material={materials.Red} position={[0.36, -0.465, -1.097]} />
      <mesh geometry={nodes.Heart_Full_cell048.geometry} material={materials.Red} position={[2.118, 0.791, -0.167]} />
      <mesh geometry={nodes.Heart_Full_cell049.geometry} material={materials.Red} position={[1.579, 1.102, -0.353]} />
      <mesh geometry={nodes.Heart_Full_cell050.geometry} material={materials.Red} position={[0.076, 0.456, 0.426]} />
      <mesh geometry={nodes.Heart_Full_cell051.geometry} material={materials.Red} position={[-0.802, 0.933, -0.989]} />
      <mesh geometry={nodes.Heart_Full_cell052.geometry} material={materials.Red} position={[0.86, 0.73, -0.705]} />
      <mesh geometry={nodes.Heart_Full_cell053.geometry} material={materials.Red} position={[-0.098, -1.955, 0.437]} />
      <mesh geometry={nodes.Heart_Full_cell054.geometry} material={materials.Red} position={[0.091, 1.215, 0.232]} />
      <mesh geometry={nodes.Heart_Full_cell055.geometry} material={materials.Red} position={[0.682, -0.634, 0.771]} />
      <mesh geometry={nodes.Heart_Full_cell056.geometry} material={materials.Red} position={[0.126, -0.064, 1.148]} />
      <mesh geometry={nodes.Heart_Full_cell057.geometry} material={materials.Red} position={[-1.252, -1.019, -0.68]} />
      <mesh geometry={nodes.Heart_Full_cell058.geometry} material={materials.Red} position={[0.945, 0.816, 1.139]} />
      <mesh geometry={nodes.Heart_Full_cell059.geometry} material={materials.Red} position={[1.589, -0.356, 0.773]} />
      <mesh geometry={nodes.Heart_Full_cell060.geometry} material={materials.Red} position={[1.92, 0.027, 0.91]} />
      <mesh geometry={nodes.Heart_Full_cell061.geometry} material={materials.Red} position={[-2.321, 0.315, -0.099]} />
      <mesh geometry={nodes.Heart_Full_cell063.geometry} material={materials.Red} position={[-1.908, 0.734, 0.484]} />
      <mesh geometry={nodes.origin.geometry} material={materials.Red} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
    </group>
  )
}

useGLTF.preload('/heart.glb')
