const vars = {
  nearRockMaxX: 13,
  nearRockN: 2,
  nearRockSpeed: 0.8,
  nearRockScale: 0.07,
  nearRockZposition: 3,
  farRockMaxX: 9,
  farRockN: 3,
  farRockSpeed: 0.77,
  farRockScale: 0.05,
  farRockZposition: 1.7,
  distantRockMaxX: 10,
  distantRockN: 4,
  distantRockSpeed: 0.7,
  distantRockScale: 0.04,
  distantRockZposition: -4.5,
  lampMaxX: 30,
  lampN: 8,
  lampSpeed: 0.75,
  lampScale: 0.7,
  lampZpoistion: -2,
  nearTreeMaxX: 27,
  nearTreeN: 5,
  nearTreeSpeed: 0.72,
  nearTreeScale: 0.12,
  nearTreeZposition: -4,
  farTreeMaxX: 8,
  farTreeN: 8,
  farTreeSpeed: 0.6,
  farTreeScale: 0.1,
  farTreeZposition: -5,
  distantTreeMaxX: 48,
  distantTreeN: 12,
  distantTreeSpeed: 0.55,
  distantTreeScale: 0.09,
  distantTreeZposition: -8,
};

export { vars };
