const vars = {
  rocksMaxX: 20,
  rocksN: 4,
  rocksSpeed: 1,
  rockScale: 0.07,
  rockZposition: 2.5,
  lampMaxX: 30,
  lampN: 10,
  lampSpeed: 0.8,
  lampScale: 0.7,
  lampZpoistion: -2,
  nearTreeMaxX: 27,
  nearTreeN: 7,
  nearTreeSpeed: 0.7,
  nearTreeScale: 0.12,
  nearTreeZposition: -4,
  farTreeMaxX: 8,
  farTreeN: 10,
  farTreeSpeed: 0.6,
  farTreeScale: 0.1,
  farTreeZposition: -5,
  distantTreeMaxX: 48,
  distantTreeN: 15,
  distantTreeSpeed: 0.5,
  distantTreeScale: 0.09,
  distantTreeZposition: -8,
};

export { vars };
