const vars = {
  nearRockMaxX: 20,
  nearRockN: 4,
  nearRockSpeed: 1,
  nearRockScale: 0.07,
  nearRockZposition: 3,
  farRockMaxX: 15,
  farRockN: 5,
  farRockSpeed: 0.9,
  farRockScale: 0.05,
  farRockZposition: 1.7,
  distantRockMaxX: 10,
  distantRockN: 4,
  distantRockSpeed: 0.5,
  distantRockScale: 0.04,
  distantRockZposition: -4.5,
  lampMaxX: 30,
  lampN: 10,
  lampSpeed: 0.8,
  lampScale: 0.7,
  lampZpoistion: -2,
  nearTreeMaxX: 27,
  nearTreeN: 7,
  nearTreeSpeed: 0.7,
  nearTreeScale: 0.12,
  nearTreeZposition: -4,
  farTreeMaxX: 8,
  farTreeN: 10,
  farTreeSpeed: 0.6,
  farTreeScale: 0.1,
  farTreeZposition: -5,
  distantTreeMaxX: 48,
  distantTreeN: 15,
  distantTreeSpeed: 0.5,
  distantTreeScale: 0.09,
  distantTreeZposition: -8,
};

export { vars };
